What is new 0.2.0
kabanero-io/blogs pull request #22
Opened 2019-10-20 17:39 UTC by erpenbach

2019-10-20 17:40 UTC, erpenbach commented
Created What's New in 0.2.0 document

2019-10-20 17:51 UTC, alohr51 requested changes

2019-10-20 17:51 UTC, alohr51 commented on publish/2019-10-20-WhatsNew020.adoc
> +image::/img/guide/Kabanero020.png[link="/img/Kabanero020.png" alt="Kabanero 0.2.0"]
this is the first img we're adding to blogs, so the below image file should go in a folder `img` at the root of the repo. Then both links would be `/img/blog/Kabanero020`

2019-10-20 18:58 UTC, alohr51 commented
we should make sure the content aligns with Nate's update to the what's new doc in this PR: https://github.com/kabanero-io/docs/pull/148

2019-10-21 20:13 UTC, alohr51 commented
should remove the img at `publish/img/Kabanero020.png ` looks like both are in the PR now.

2019-10-21 20:14 UTC, alohr51 commented
and the link needs to change as described in https://github.com/kabanero-io/blogs/pull/22/files#r336788961

2019-10-22 14:40 UTC, erpenbach commented on publish/2019-10-20-WhatsNew020.adoc
> +image::/img/guide/Kabanero020.png[link="/img/Kabanero020.png" alt="Kabanero 0.2.0"]
I've updated to put the png file in /img/blog/

2019-10-22 14:54 UTC, nateziemann commented on publish/2019-10-20-WhatsNew020.adoc
> +seo-description: What is new in the 0.2.0 release - this covers the new namespace support, ease of use enhancements and guides.
seo-description: What is new in 0.2.0 - New CLI, Collections enhanced, Kubernetes Application Navigator, Guides, Kabanero operator enhanced

2019-10-22 14:55 UTC, nateziemann commented on publish/2019-10-20-WhatsNew020.adoc
> +blog_description: "What is new in the 0.2.0 release - this covers the new namespace support, ease of use enhancements and guides."
blog_description: What is new in 0.2.0 - New CLI, Collections enhanced, Kubernetes Application Navigator, Guides, Kabanero operator enhanced

2019-10-22 17:45 UTC, alohr51 approved these changes

2019-10-22 17:46 UTC, merged